server:
  port: 8080
  servlet:
    context-path: /sound-cloud/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sound_cloud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: soundcloudk04@gmail.com
    password: navbmpjhrhuzerjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: o7puuzmv68t5qfzl1wagao4ymn37w1e0v65l7vvz0mto3jhrrd1r02biymloilub
  issuer: tungnn
  valid-duration: 360000
  refreshable-duration: 3600000

cloudinary:
  name: dcwopmt83
  api-key: 113135811718677
  api-secret: IElyDCaO1LR7JLVEKmoh1K5ZdwQ